using System;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using System.Text.Json;
using MathNet.Numerics.LinearAlgebra.Single;

namespace DroneLiDAR
{
    public readonly struct VolumeBalance
    {
        public readonly double CutVolume;
        public readonly double FillVolume;
        public readonly double NetVolume;
        public readonly double BulkedVolume;
        public readonly double MaterialWeightTon;
        public readonly double AreaCut;
        public readonly double AreaFill;
        public readonly double MaxDepth;
        public readonly double RmseElevation;
        public readonly int StableCellCount;
        public readonly double CoveragePercent;
        public readonly float DemCellSize;

        public VolumeBalance(double cut, double fill, double areaCut, double areaFill, double maxDepth,
                             float density, float bulkingFactor, double rmse,
                             int stableCellCount = 0, double coveragePercent = 0.0,
                             float demCellSize = float.NaN)
        {
            CutVolume = cut;
            FillVolume = fill;
            NetVolume = cut - fill;
            BulkedVolume = cut * bulkingFactor;
            MaterialWeightTon = CutVolume * density;
            AreaCut = areaCut;
            AreaFill = areaFill;
            MaxDepth = maxDepth;
            RmseElevation = rmse;
            StableCellCount = stableCellCount;
            CoveragePercent = coveragePercent;
            DemCellSize = demCellSize;
        }
    }

    public class BoundaryPolygon
    {
        public List<Vector2> Vertices { get; set; } = new List<Vector2>();
        public bool IsAutoGenerated { get; set; }

        public bool IsPointInside(float x, float y)
        {
            if (Vertices == null || Vertices.Count < 3) return true;

            bool inside = false;
            int j = Vertices.Count - 1;

            for (int i = 0; i < Vertices.Count; i++)
            {
                var vi = Vertices[i];
                var vj = Vertices[j];

                if (((vi.Y > y) != (vj.Y > y)) &&
                    (x < (vj.X - vi.X) * (y - vi.Y) / (vj.Y - vi.Y) + vi.X))
                {
                    inside = !inside;
                }
                j = i;
            }

            return inside;
        }

        public void Save(string dir)
        {
            if (!IsValid()) throw new InvalidDataException("Нельзя сохранить невалидный AOI.");
            string jsonPath = Path.Combine(dir, "boundary.json");
            string temporaryPath = jsonPath + ".tmp";
            File.WriteAllText(temporaryPath, JsonSerializer.Serialize(this, JsonOptions(true)));
            File.Move(temporaryPath, jsonPath, true);
        }

        public static BoundaryPolygon? TryLoad(string dir, ProjectConfig? project = null)
        {
            string geoJsonPath = Path.Combine(dir, "boundary.geojson");
            if (File.Exists(geoJsonPath))
            {
                try
                {
                    var poly = ParseGeoJsonPolygon(File.ReadAllText(geoJsonPath), project);
                    if (poly.IsValid()) return poly;
                    throw new InvalidDataException("GeoJSON не содержит валидный полигон.");
                }
                catch (Exception ex) when (ex is JsonException
                    || ex is InvalidDataException
                    || ex is IOException
                    || ex is UnauthorizedAccessException)
                {
                    throw new InvalidDataException(
                        $"Не удалось прочитать AOI {geoJsonPath}: {ex.Message}",
                        ex);
                }
            }

            string jsonPath = Path.Combine(dir, "boundary.json");
            if (File.Exists(jsonPath))
            {
                try
                {
                    var poly = JsonSerializer.Deserialize<BoundaryPolygon>(File.ReadAllText(jsonPath), JsonOptions(false));
                    if (poly != null && poly.IsValid()) return poly;
                    throw new InvalidDataException("JSON не содержит валидный полигон.");
                }
                catch (Exception ex) when (ex is JsonException
                    || ex is InvalidDataException
                    || ex is IOException
                    || ex is UnauthorizedAccessException)
                {
                    throw new InvalidDataException(
                        $"Не удалось прочитать AOI {jsonPath}: {ex.Message}",
                        ex);
                }
            }

            return null;
        }

        public static BoundaryPolygon LoadOrCreate(string dir, float defaultRadius = 12.0f, ProjectConfig? project = null)
        {
            var loaded = TryLoad(dir, project);
            if (loaded != null) return loaded;

            var defaultPoly = CreateCircle(defaultRadius);
            defaultPoly.Save(dir);
            return defaultPoly;
        }

        public static BoundaryPolygon CreateCircle(float radius, int segments = 16)
        {
            var poly = new BoundaryPolygon { IsAutoGenerated = true };
            for (int i = 0; i < segments; i++)
            {
                float angle = i * MathF.PI * 2.0f / segments;
                poly.Vertices.Add(new Vector2(MathF.Cos(angle) * radius, MathF.Sin(angle) * radius));
            }
            return poly;
        }

        public static BoundaryPolygon CreateInsetFromCloud(List<Point3D> points, float marginFraction = 0.12f, float minMargin = 4.0f)
        {
            float minX = float.MaxValue, minY = float.MaxValue;
            float maxX = float.MinValue, maxY = float.MinValue;

            for (int i = 0; i < points.Count; i++)
            {
                var pt = points[i];
                if (pt.X < minX) minX = pt.X; if (pt.X > maxX) maxX = pt.X;
                if (pt.Y < minY) minY = pt.Y; if (pt.Y > maxY) maxY = pt.Y;
            }

            float width = Math.Max(1.0f, maxX - minX);
            float height = Math.Max(1.0f, maxY - minY);
            float margin = Math.Max(minMargin, Math.Min(width, height) * marginFraction);

            float x0 = minX + margin;
            float y0 = minY + margin;
            float x1 = maxX - margin;
            float y1 = maxY - margin;
            if (x1 <= x0 || y1 <= y0)
            {
                x0 = minX; y0 = minY; x1 = maxX; y1 = maxY;
            }

            var poly = new BoundaryPolygon { IsAutoGenerated = true };
            poly.Vertices.Add(new Vector2(x0, y0));
            poly.Vertices.Add(new Vector2(x1, y0));
            poly.Vertices.Add(new Vector2(x1, y1));
            poly.Vertices.Add(new Vector2(x0, y1));
            return poly;
        }

        public bool IsValid()
        {
            if (Vertices == null || Vertices.Count < 3) return false;
            double twiceArea = 0;
            for (int i = 0, j = Vertices.Count - 1; i < Vertices.Count; j = i++)
            {
                if (!float.IsFinite(Vertices[i].X) || !float.IsFinite(Vertices[i].Y)) return false;
                twiceArea += (double)Vertices[j].X * Vertices[i].Y
                    - (double)Vertices[i].X * Vertices[j].Y;
            }
            return Math.Abs(twiceArea) > 0.02;
        }

        private static JsonSerializerOptions JsonOptions(bool indented) => new JsonSerializerOptions
        {
            WriteIndented = indented,
            IncludeFields = true
        };

        private static BoundaryPolygon ParseGeoJsonPolygon(string geoJson, ProjectConfig? project)
        {
            var poly = new BoundaryPolygon();
            using var doc = JsonDocument.Parse(geoJson);
            var root = doc.RootElement;

            JsonElement coordsArray = default;
            if (root.TryGetProperty("geometry", out var geom) && geom.TryGetProperty("coordinates", out var coords))
                coordsArray = coords[0];
            else if (root.TryGetProperty("coordinates", out var coordsDirect))
                coordsArray = coordsDirect[0];

            if (coordsArray.ValueKind == JsonValueKind.Array)
            {
                foreach (var pt in coordsArray.EnumerateArray())
                {
                    double x = pt[0].GetDouble();
                    double y = pt[1].GetDouble();
                    if (project != null && project.IsInitialized && Math.Abs(x) > 10000.0)
                    {
                        x -= project.OriginX;
                        y -= project.OriginY;
                    }
                    poly.Vertices.Add(new Vector2((float)x, (float)y));
                }
            }
            return poly;
        }
    }

    public static class MathApparatus
    {
        public static List<Point3D> ClassifyGroundAndObjects(List<Point3D> points, float gridCellSize = 0.5f, float heightThreshold = 0.25f)
        {
            if (points == null || points.Count == 0) return new List<Point3D>();
            if (!float.IsFinite(gridCellSize) || gridCellSize <= 0)
                throw new ArgumentOutOfRangeException(nameof(gridCellSize));

            float minX = float.MaxValue, minY = float.MaxValue;
            float maxX = float.MinValue, maxY = float.MinValue;

            for (int i = 0; i < points.Count; i++)
            {
                var pt = points[i];
                if (pt.X < minX) minX = pt.X; if (pt.X > maxX) maxX = pt.X;
                if (pt.Y < minY) minY = pt.Y; if (pt.Y > maxY) maxY = pt.Y;
            }

            const double MaxClassificationCells = 8_000_000;
            double initialCols = Math.Ceiling((maxX - minX) / gridCellSize) + 1;
            double initialRows = Math.Ceiling((maxY - minY) / gridCellSize) + 1;
            if (!double.IsFinite(initialCols) || !double.IsFinite(initialRows)
                || initialCols > 100_000 || initialRows > 100_000)
            {
                throw new InvalidDataException("Границы облака слишком велики для классификации. Проверьте CRS и выбросы.");
            }
            double initialCells = initialCols * initialRows;
            if (initialCells > MaxClassificationCells)
            {
                gridCellSize *= (float)Math.Sqrt(initialCells / MaxClassificationCells);
            }

            int cols = Math.Max(1, (int)MathF.Ceiling((maxX - minX) / gridCellSize) + 1);
            int rows = Math.Max(1, (int)MathF.Ceiling((maxY - minY) / gridCellSize) + 1);
            int totalCells = cols * rows;

            float[] minElevationGrid = new float[totalCells];
            float[] maxElevationGrid = new float[totalCells];
            int[] pointCountGrid = new int[totalCells];
            int[] machineryColorGrid = new int[totalCells];
            Array.Fill(minElevationGrid, float.MaxValue);
            Array.Fill(maxElevationGrid, float.MinValue);

            for (int i = 0; i < points.Count; i++)
            {
                var pt = points[i];
                int c = (int)((pt.X - minX) / gridCellSize);
                int r = (int)((pt.Y - minY) / gridCellSize);
                if (c < 0 || c >= cols || r < 0 || r >= rows) continue;
                int idx = r * cols + c;

                bool participatesInHeuristic = pt.Classification == 0
                    || pt.Classification == Point3D.ClassUnclassified
                    || pt.Classification == Point3D.ClassGround;
                if (!participatesInHeuristic) continue;

                if (pt.Z > maxElevationGrid[idx]) maxElevationGrid[idx] = pt.Z;
                pointCountGrid[idx]++;
                if (IsMachineryColor(pt)) machineryColorGrid[idx]++;

                if (!pt.IsLastReturn && pt.NumberOfReturns > 1) continue;
                if (pt.Z < minElevationGrid[idx]) minElevationGrid[idx] = pt.Z;
            }

            float[] smoothedGround = SmoothGrid(minElevationGrid, cols, rows);

            byte[] cellKind = new byte[totalCells];
            bool[] elevated = new bool[totalCells];
            for (int i = 0; i < totalCells; i++)
            {
                if (minElevationGrid[i] >= float.MaxValue - 100f || maxElevationGrid[i] <= float.MinValue + 100f)
                    continue;
                float thickness = maxElevationGrid[i] - minElevationGrid[i];
                elevated[i] = thickness > 0.70f;
            }

            LabelElevatedComponents(
                elevated,
                maxElevationGrid,
                smoothedGround,
                pointCountGrid,
                machineryColorGrid,
                cols,
                rows,
                gridCellSize,
                cellKind);

            var classified = new List<Point3D>(points.Count);
            for (int i = 0; i < points.Count; i++)
            {
                var pt = points[i];
                int c = (int)((pt.X - minX) / gridCellSize);
                int r = (int)((pt.Y - minY) / gridCellSize);

                byte cls = pt.Classification;
                if (c >= 0 && c < cols && r >= 0 && r < rows)
                {
                    int idx = r * cols + c;
                    float groundZ = smoothedGround[idx];
                    float above = groundZ < float.MaxValue - 100f ? pt.Z - groundZ : 0f;
                    float aboveLocalMinimum = minElevationGrid[idx] < float.MaxValue - 100f
                        ? pt.Z - minElevationGrid[idx]
                        : 0f;
                    byte kind = cellKind[idx];

                    // Доверяем явной классификации входного LAS. Геометрическая
                    // эвристика нужна только для неклассифицированных точек.
                    if (pt.Classification == Point3D.ClassMachinery)
                    {
                        cls = Point3D.ClassMachinery;
                    }
                    else if (pt.Classification == Point3D.ClassGround)
                    {
                        cls = Point3D.ClassGround;
                    }
                    else if (pt.Classification == Point3D.ClassBuilding
                        || pt.Classification == Point3D.ClassWater
                        || pt.Classification == Point3D.ClassBridge
                        || pt.Classification == Point3D.ClassMaterial)
                    {
                        cls = pt.Classification;
                    }
                    else if (pt.Classification == Point3D.ClassLowVeg
                        || pt.Classification == Point3D.ClassMediumVeg
                        || pt.Classification == Point3D.ClassHighVeg
                        || pt.Classification == Point3D.ClassNoise
                        || pt.Classification == Point3D.ClassHighNoise
                        || pt.Classification == Point3D.ClassOverlap)
                    {
                        cls = pt.Classification;
                    }
                    else if (pt.Classification != 0
                        && pt.Classification != Point3D.ClassUnclassified)
                    {
                        // Неизвестные пользовательские/стандартные классы сохраняются
                        // и консервативно не допускаются в DEM.
                        cls = pt.Classification;
                    }
                    else if (!pt.IsLastReturn && pt.NumberOfReturns > 1 && above > heightThreshold)
                    {
                        cls = Point3D.ClassLowVeg;
                    }
                    else if (kind == Point3D.ClassMachinery
                        && above > heightThreshold
                        && (IsMachineryColor(pt) || aboveLocalMinimum > 0.45f))
                    {
                        cls = Point3D.ClassMachinery;
                    }
                    else if (kind == Point3D.ClassHighVeg && above > heightThreshold)
                    {
                        cls = Point3D.ClassHighVeg;
                    }
                    else if (kind == Point3D.ClassLowVeg && above > heightThreshold)
                    {
                        cls = Point3D.ClassLowVeg;
                    }
                    else if (above > heightThreshold)
                    {
                        cls = Point3D.ClassGround;
                    }
                    else
                    {
                        cls = Point3D.ClassGround;
                    }
                }

                classified.Add(new Point3D(pt.X, pt.Y, pt.Z, pt.R, pt.G, pt.B, cls, pt.ReturnInfo));
            }

            return classified;
        }

        private static float[] SmoothGrid(float[] source, int cols, int rows)
        {
            float[] smoothed = new float[source.Length];
            Array.Copy(source, smoothed, source.Length);

            for (int r = 0; r < rows; r++)
            {
                for (int c = 0; c < cols; c++)
                {
                    int idx = r * cols + c;
                    if (source[idx] >= float.MaxValue - 100f) continue;

                    float sum = 0;
                    int count = 0;
                    for (int dr = -1; dr <= 1; dr++)
                    {
                        for (int dc = -1; dc <= 1; dc++)
                        {
                            int rr = r + dr, cc = c + dc;
                            if (rr < 0 || rr >= rows || cc < 0 || cc >= cols) continue;
                            float val = source[rr * cols + cc];
                            if (val < float.MaxValue - 100f)
                            {
                                sum += val;
                                count++;
                            }
                        }
                    }
                    if (count > 0) smoothed[idx] = sum / count;
                }
            }

            return smoothed;
        }

        private static bool IsMachineryColor(Point3D pt)
        {
            bool yellowOrOrange = pt.R > 190
                && pt.G > 85
                && pt.G < 225
                && pt.B < 90
                && pt.R > pt.G * 1.12f;
            bool cyanOrBlue = pt.B > 125
                && pt.G > 105
                && pt.R < 110;
            return yellowOrOrange || cyanOrBlue;
        }

        private static void LabelElevatedComponents(
            bool[] elevated,
            float[] maxZ,
            float[] ground,
            int[] pointCount,
            int[] machineryColorCount,
            int cols,
            int rows,
            float cellSize,
            byte[] cellKind)
        {
            int total = cols * rows;
            int[] labels = new int[total];
            Array.Fill(labels, -1);
            int current = 0;
            var stack = new Stack<int>();
            var componentCells = new List<int>();

            for (int start = 0; start < total; start++)
            {
                if (!elevated[start] || labels[start] >= 0) continue;

                int minC = cols, maxC = 0, minR = rows, maxR = 0, nCells = 0;
                int componentPoints = 0, componentMachineryColors = 0;
                float maxHeight = 0;
                componentCells.Clear();
                stack.Push(start);
                labels[start] = current;

                while (stack.Count > 0)
                {
                    int idx = stack.Pop();
                    componentCells.Add(idx);
                    int r = idx / cols;
                    int c = idx - r * cols;
                    nCells++;
                    if (c < minC) minC = c; if (c > maxC) maxC = c;
                    if (r < minR) minR = r; if (r > maxR) maxR = r;
                    componentPoints += pointCount[idx];
                    componentMachineryColors += machineryColorCount[idx];
                    if (ground[idx] < float.MaxValue - 100f)
                    {
                        float h = maxZ[idx] - ground[idx];
                        if (h > maxHeight) maxHeight = h;
                    }

                    for (int dr = -1; dr <= 1; dr++)
                    {
                        for (int dc = -1; dc <= 1; dc++)
                        {
                            if (dr == 0 && dc == 0) continue;
                            int rr = r + dr, cc = c + dc;
                            if (rr < 0 || rr >= rows || cc < 0 || cc >= cols) continue;
                            int nidx = rr * cols + cc;
                            if (!elevated[nidx] || labels[nidx] >= 0) continue;
                            labels[nidx] = current;
                            stack.Push(nidx);
                        }
                    }
                }

                float area = nCells * cellSize * cellSize;
                float sizeX = (maxC - minC + 1) * cellSize;
                float sizeY = (maxR - minR + 1) * cellSize;
                float maxDim = MathF.Max(sizeX, sizeY);
                float machineryColorRatio = componentPoints > 0
                    ? componentMachineryColors / (float)componentPoints
                    : 0.0f;

                byte kind = Point3D.ClassGround;
                if (area >= 2.5f
                    && area <= 55.0f
                    && maxDim <= 18.0f
                    && maxHeight >= 1.2f
                    && maxHeight <= 6.5f
                    && machineryColorRatio >= 0.05f)
                {
                    kind = Point3D.ClassMachinery;
                }

                if (kind != Point3D.ClassGround)
                {
                    for (int i = 0; i < componentCells.Count; i++)
                    {
                        int idx = componentCells[i];
                        if (kind == Point3D.ClassMachinery
                            && !HasMachineryColorNearby(idx, machineryColorCount, cols, rows, 2))
                        {
                            continue;
                        }
                        cellKind[idx] = kind;
                    }
                }

                current++;
            }
        }

        private static bool HasMachineryColorNearby(
            int index,
            int[] machineryColorCount,
            int cols,
            int rows,
            int radius)
        {
            int row = index / cols;
            int col = index - row * cols;
            for (int dr = -radius; dr <= radius; dr++)
            {
                for (int dc = -radius; dc <= radius; dc++)
                {
                    int rr = row + dr;
                    int cc = col + dc;
                    if (rr < 0 || rr >= rows || cc < 0 || cc >= cols) continue;
                    if (machineryColorCount[rr * cols + cc] > 0) return true;
                }
            }
            return false;
        }

        public static VolumeBalance CalculateVolumeBalance(List<Point3D> baseCloud, List<Point3D> currentCloud,
                                                           float cellSize, BoundaryPolygon? aoi,
                                                           float materialDensity, float bulkingFactor,
                                                           bool filterMachinery = true, string? exportGridCsv = null)
        {
            if (baseCloud == null || currentCloud == null || baseCloud.Count == 0 || currentCloud.Count == 0)
                return new VolumeBalance(0, 0, 0, 0, 0, materialDensity, bulkingFactor, double.NaN);
            if (!float.IsFinite(cellSize) || cellSize <= 0)
                throw new ArgumentOutOfRangeException(nameof(cellSize), "Шаг DEM должен быть положительным.");
            if (aoi != null && !aoi.IsValid())
                throw new InvalidDataException("Контур AOI пуст или имеет нулевую площадь.");

            float minX = float.MaxValue, minY = float.MaxValue;
            float maxX = float.MinValue, maxY = float.MinValue;

            if (aoi != null)
            {
                for (int i = 0; i < aoi.Vertices.Count; i++)
                {
                    Vector2 vertex = aoi.Vertices[i];
                    if (vertex.X < minX) minX = vertex.X;
                    if (vertex.X > maxX) maxX = vertex.X;
                    if (vertex.Y < minY) minY = vertex.Y;
                    if (vertex.Y > maxY) maxY = vertex.Y;
                }
                float stableMargin = Math.Max(10.0f, cellSize * 20.0f);
                minX -= stableMargin;
                minY -= stableMargin;
                maxX += stableMargin;
                maxY += stableMargin;
            }
            else
            {
                ExpandBounds(baseCloud, ref minX, ref minY, ref maxX, ref maxY);
                ExpandBounds(currentCloud, ref minX, ref minY, ref maxX, ref maxY);
            }

            const double MaxDemCells = 25_000_000;
            const double MaxDemSide = 100_000;
            double width = maxX - minX;
            double height = maxY - minY;
            double colsDouble = Math.Ceiling(width / cellSize) + 1;
            double rowsDouble = Math.Ceiling(height / cellSize) + 1;
            float requestedCellSize = cellSize;
            if (colsDouble > MaxDemSide || rowsDouble > MaxDemSide || colsDouble * rowsDouble > MaxDemCells)
            {
                double areaLimitedStep = Math.Sqrt(Math.Max(0.0, width * height) / (MaxDemCells * 0.98));
                double sideLimitedStep = Math.Max(width / (MaxDemSide - 1), height / (MaxDemSide - 1));
                long baseSamples = CountDemSamplesInBounds(
                    baseCloud, minX, minY, maxX, maxY, filterMachinery);
                long currentSamples = CountDemSamplesInBounds(
                    currentCloud, minX, minY, maxX, maxY, filterMachinery);
                long limitingSamples = Math.Min(baseSamples, currentSamples);
                double densityLimitedStep = limitingSamples > 0
                    ? Math.Sqrt(width * height * 3.0 / limitingSamples)
                    : 0.0;
                cellSize = (float)Math.Max(
                    cellSize,
                    Math.Max(densityLimitedStep, Math.Max(areaLimitedStep, sideLimitedStep)));
                if (!float.IsFinite(cellSize) || cellSize <= 0)
                    throw new InvalidDataException(
                        "Размер DEM невозможно определить. Проверьте CRS и координаты AOI.");

                colsDouble = Math.Ceiling(width / cellSize) + 1;
                rowsDouble = Math.Ceiling(height / cellSize) + 1;
                while (colsDouble > MaxDemSide || rowsDouble > MaxDemSide || colsDouble * rowsDouble > MaxDemCells)
                {
                    cellSize *= 1.01f;
                    colsDouble = Math.Ceiling(width / cellSize) + 1;
                    rowsDouble = Math.Ceiling(height / cellSize) + 1;
                }
                Console.WriteLine(
                    $"  [DEM] зона {width:F1}×{height:F1} м: шаг автоматически увеличен "
                    + $"{requestedCellSize:F3} → {cellSize:F3} м с учётом плотности обеих эпох и памяти.");
            }
            int cols = Math.Max(1, (int)colsDouble);
            int rows = Math.Max(1, (int)rowsDouble);

            DemGrid baseGrid = BuildRobustDEM(baseCloud, cellSize, minX, minY, cols, rows, filterMachinery);
            DemGrid currentGrid = BuildRobustDEM(currentCloud, cellSize, minX, minY, cols, rows, filterMachinery);

            InterpolateSmallHoles(baseGrid, cols, rows);
            InterpolateSmallHoles(currentGrid, cols, rows);

            double totalCut = 0.0;
            double totalFill = 0.0;
            double areaCut = 0.0;
            double areaFill = 0.0;
            double maxDepth = 0.0;
            double cellArea = cellSize * cellSize;
            float minDiff = Math.Max(0.03f, Math.Min(0.10f, cellSize * 0.15f));

            double sumSquaredErrors = 0.0;
            int stableCount = 0;
            int insideCellCount = 0;
            int validInsideCellCount = 0;

            for (int r = 0; r < rows; r++)
            {
                float cellCenterY = minY + (r + 0.5f) * cellSize;
                for (int c = 0; c < cols; c++)
                {
                    float cellCenterX = minX + (c + 0.5f) * cellSize;
                    int idx = r * cols + c;
                    bool insideAOI = aoi == null || aoi.IsPointInside(cellCenterX, cellCenterY);
                    if (insideAOI) insideCellCount++;
                    if (!baseGrid.Valid[idx] || !currentGrid.Valid[idx]) continue;

                    float bZ = baseGrid.Values[idx];
                    float cZ = currentGrid.Values[idx];
                    float diff = bZ - cZ;

                    if (insideAOI)
                    {
                        validInsideCellCount++;
                        if (diff > minDiff)
                        {
                            totalCut += diff * cellArea;
                            areaCut += cellArea;
                            if (diff > maxDepth) maxDepth = diff;
                        }
                        else if (diff < -minDiff)
                        {
                            totalFill += Math.Abs(diff) * cellArea;
                            areaFill += cellArea;
                        }
                    }
                    else
                    {
                        sumSquaredErrors += diff * diff;
                        stableCount++;
                    }
                }
            }

            double rmse = stableCount > 10 ? Math.Sqrt(sumSquaredErrors / stableCount) : double.NaN;
            double coverage = insideCellCount > 0
                ? validInsideCellCount * 100.0 / insideCellCount
                : 0.0;

            if (!string.IsNullOrEmpty(exportGridCsv))
            {
                ReportGenerator.ExportVolumeGridCsv(
                    exportGridCsv,
                    baseGrid.Values,
                    currentGrid.Values,
                    baseGrid.Valid,
                    currentGrid.Valid,
                    minX,
                    minY,
                    cellSize,
                    cols,
                    rows,
                    aoi,
                    minDiff);
            }

            return new VolumeBalance(
                totalCut,
                totalFill,
                areaCut,
                areaFill,
                maxDepth,
                materialDensity,
                bulkingFactor,
                rmse,
                stableCount,
                coverage,
                cellSize);
        }

        private static void ExpandBounds(List<Point3D> cloud, ref float minX, ref float minY, ref float maxX, ref float maxY)
        {
            for (int i = 0; i < cloud.Count; i++)
            {
                var pt = cloud[i];
                if (pt.X < minX) minX = pt.X;
                if (pt.X > maxX) maxX = pt.X;
                if (pt.Y < minY) minY = pt.Y;
                if (pt.Y > maxY) maxY = pt.Y;
            }
        }

        private static long CountDemSamplesInBounds(
            List<Point3D> cloud,
            float minX,
            float minY,
            float maxX,
            float maxY,
            bool filterMachinery)
        {
            long count = 0;
            for (int i = 0; i < cloud.Count; i++)
            {
                Point3D point = cloud[i];
                if (point.X < minX || point.X > maxX || point.Y < minY || point.Y > maxY)
                    continue;
                if (filterMachinery && Point3D.IsExcludedFromDem(point.Classification))
                    continue;
                count++;
            }
            return count;
        }

        private sealed class DemGrid
        {
            public float[] Values { get; }
            public bool[] Measured { get; }
            public bool[] Valid { get; }

            public DemGrid(int size)
            {
                Values = new float[size];
                Measured = new bool[size];
                Valid = new bool[size];
                Array.Fill(Values, float.NaN);
            }
        }

        private readonly struct DemSample : IComparable<DemSample>
        {
            public readonly int Cell;
            public readonly float Z;

            public DemSample(int cell, float z)
            {
                Cell = cell;
                Z = z;
            }

            public int CompareTo(DemSample other)
            {
                int cellOrder = Cell.CompareTo(other.Cell);
                return cellOrder != 0 ? cellOrder : Z.CompareTo(other.Z);
            }
        }

        private static DemGrid BuildRobustDEM(List<Point3D> points, float cellSize, float minX, float minY, int cols, int rows, bool filterMachinery)
        {
            int totalCells = cols * rows;
            int sampleCount = 0;

            for (int i = 0; i < points.Count; i++)
            {
                var pt = points[i];
                if (filterMachinery && Point3D.IsExcludedFromDem(pt.Classification)) continue;

                int c = (int)((pt.X - minX) / cellSize);
                int r = (int)((pt.Y - minY) / cellSize);
                if (c < 0 || c >= cols || r < 0 || r >= rows) continue;
                sampleCount++;
            }

            var samples = new DemSample[sampleCount];
            int sampleIndex = 0;
            for (int i = 0; i < points.Count; i++)
            {
                var pt = points[i];
                if (filterMachinery && Point3D.IsExcludedFromDem(pt.Classification)) continue;

                int c = (int)((pt.X - minX) / cellSize);
                int r = (int)((pt.Y - minY) / cellSize);
                if (c < 0 || c >= cols || r < 0 || r >= rows) continue;
                samples[sampleIndex++] = new DemSample(r * cols + c, pt.Z);
            }
            Array.Sort(samples);

            var grid = new DemGrid(totalCells);
            int start = 0;
            while (start < samples.Length)
            {
                int end = start + 1;
                int cell = samples[start].Cell;
                while (end < samples.Length && samples[end].Cell == cell) end++;

                int quantileOffset = (int)Math.Round((end - start - 1) * 0.85);
                grid.Values[cell] = samples[start + quantileOffset].Z;
                grid.Measured[cell] = true;
                grid.Valid[cell] = true;
                start = end;
            }
            return grid;
        }

        private static void InterpolateSmallHoles(DemGrid grid, int cols, int rows)
        {
            float[] nextValues = (float[])grid.Values.Clone();
            bool[] nextValid = (bool[])grid.Valid.Clone();
            for (int r = 0; r < rows; r++)
            {
                for (int c = 0; c < cols; c++)
                {
                    int idx = r * cols + c;
                    if (grid.Valid[idx]) continue;

                    float sum = 0;
                    int count = 0;
                    for (int dr = -1; dr <= 1; dr++)
                    {
                        for (int dc = -1; dc <= 1; dc++)
                        {
                            if (dr == 0 && dc == 0) continue;
                            int rr = r + dr, cc = c + dc;
                            if (rr < 0 || rr >= rows || cc < 0 || cc >= cols) continue;
                            int neighbor = rr * cols + cc;
                            if (grid.Valid[neighbor] && grid.Measured[neighbor])
                            {
                                sum += grid.Values[neighbor];
                                count++;
                            }
                        }
                    }
                    if (count >= 5)
                    {
                        nextValues[idx] = sum / count;
                        nextValid[idx] = true;
                    }
                }
            }
            Array.Copy(nextValues, grid.Values, grid.Values.Length);
            Array.Copy(nextValid, grid.Valid, grid.Valid.Length);
        }

        public static (Matrix4x4 Transform, float Error, bool IsReliable) AlignCloudsICP(
            List<Vector3> source, List<Vector3> target, int maxIterations = 8, float maxAllowedShift = 0.35f)
        {
            if (source.Count < 300 || target.Count < 300)
                return (Matrix4x4.Identity, float.PositiveInfinity, false);

            source = Subsample(source, 25000);
            target = Subsample(target, 25000);

            var kdTree = new KdTreeFlat(target);
            Matrix4x4 globalTransform = Matrix4x4.Identity;
            float lastError = float.MaxValue;
            var currentSource = new List<Vector3>(source);
            bool hadSolution = false;
            int lastInlierCount = 0;
            float lastOverlap = 0;

            for (int iter = 0; iter < maxIterations; iter++)
            {
                var pointPairs = new List<(Vector3 Src, Vector3 Tgt, float DistSq)>(currentSource.Count / 4);
                var distances = new List<float>(currentSource.Count / 4);

                for (int i = 0; i < currentSource.Count; i += 4)
                {
                    var sPt = currentSource[i];
                    var (bestPt, bestDistSq) = kdTree.FindNearest(sPt);
                    if (bestDistSq < 4.0f)
                    {
                        pointPairs.Add((sPt, bestPt, bestDistSq));
                        distances.Add(bestDistSq);
                    }
                }

                int sampledCount = Math.Max(1, (currentSource.Count + 3) / 4);
                lastOverlap = pointPairs.Count / (float)sampledCount;
                if (pointPairs.Count < 30 || lastOverlap < 0.15f)
                    return (Matrix4x4.Identity, float.PositiveInfinity, false);

                distances.Sort();
                float medianDistSq = distances[distances.Count / 2];
                float cutoffThreshold = Math.Max(medianDistSq * 2.5f, 0.005f);

                var matchedSource = new List<Vector3>(pointPairs.Count);
                var matchedTarget = new List<Vector3>(pointPairs.Count);
                float currentError = 0;
                int keepCount = 0;

                for (int i = 0; i < pointPairs.Count; i++)
                {
                    if (pointPairs[i].DistSq <= cutoffThreshold)
                    {
                        matchedSource.Add(pointPairs[i].Src);
                        matchedTarget.Add(pointPairs[i].Tgt);
                        currentError += MathF.Sqrt(pointPairs[i].DistSq);
                        keepCount++;
                    }
                }

                if (keepCount < 30)
                    return (Matrix4x4.Identity, float.PositiveInfinity, false);
                currentError /= keepCount;
                lastInlierCount = keepCount;
                hadSolution = true;
                if (MathF.Abs(lastError - currentError) < 0.0001f)
                {
                    lastError = currentError;
                    break;
                }
                lastError = currentError;

                var (R, T) = CalculateRigidTransformationSVD(matchedSource, matchedTarget);
                Matrix4x4 stepTransform = new Matrix4x4(
                    R[0, 0], R[1, 0], R[2, 0], 0,
                    R[0, 1], R[1, 1], R[2, 1], 0,
                    R[0, 2], R[1, 2], R[2, 2], 0,
                    T.X, T.Y, T.Z, 1
                );

                globalTransform = globalTransform * stepTransform;
                for (int i = 0; i < currentSource.Count; i++)
                    currentSource[i] = Vector3.Transform(currentSource[i], stepTransform);
            }

            float totalShift = new Vector3(globalTransform.M41, globalTransform.M42, globalTransform.M43).Length();
            float trace = globalTransform.M11 + globalTransform.M22 + globalTransform.M33;
            float rotationDegrees = MathF.Acos(Math.Clamp((trace - 1.0f) * 0.5f, -1.0f, 1.0f)) * 180.0f / MathF.PI;
            bool reliable = hadSolution
                && lastInlierCount >= 30
                && lastOverlap >= 0.15f
                && float.IsFinite(lastError)
                && lastError <= 0.25f
                && totalShift <= maxAllowedShift
                && rotationDegrees <= 3.0f;

            return reliable
                ? (globalTransform, lastError, true)
                : (Matrix4x4.Identity, float.IsFinite(lastError) ? lastError : float.PositiveInfinity, false);
        }

        private static List<Vector3> Subsample(List<Vector3> points, int maxCount)
        {
            if (points.Count <= maxCount) return points;
            var ranked = new (uint Hash, int Index)[points.Count];
            for (int i = 0; i < points.Count; i++)
                ranked[i] = (SpatialHash(points[i]), i);
            Array.Sort(ranked, (a, b) => a.Hash.CompareTo(b.Hash));
            var sampled = new List<Vector3>(maxCount);
            for (int i = 0; i < maxCount; i++) sampled.Add(points[ranked[i].Index]);
            return sampled;
        }

        private static uint SpatialHash(Vector3 point)
        {
            unchecked
            {
                int x = (int)MathF.Round(point.X * 1000);
                int y = (int)MathF.Round(point.Y * 1000);
                int z = (int)MathF.Round(point.Z * 1000);
                uint hash = 2166136261;
                hash = (hash ^ (uint)x) * 16777619;
                hash = (hash ^ (uint)y) * 16777619;
                hash = (hash ^ (uint)z) * 16777619;
                return hash;
            }
        }

        private static (DenseMatrix Rotation, Vector3 Translation) CalculateRigidTransformationSVD(List<Vector3> src, List<Vector3> dst)
        {
            int n = src.Count;
            Vector3 centroidSrc = Vector3.Zero, centroidDst = Vector3.Zero;
            for (int i = 0; i < n; i++)
            {
                centroidSrc += src[i];
                centroidDst += dst[i];
            }
            centroidSrc /= n;
            centroidDst /= n;

            var H = DenseMatrix.Create(3, 3, 0f);
            for (int i = 0; i < n; i++)
            {
                var s = src[i] - centroidSrc;
                var d = dst[i] - centroidDst;
                H[0, 0] += s.X * d.X; H[0, 1] += s.X * d.Y; H[0, 2] += s.X * d.Z;
                H[1, 0] += s.Y * d.X; H[1, 1] += s.Y * d.Y; H[1, 2] += s.Y * d.Z;
                H[2, 0] += s.Z * d.X; H[2, 1] += s.Z * d.Y; H[2, 2] += s.Z * d.Z;
            }

            var svd = H.Svd();
            var R = (DenseMatrix)(svd.VT.Transpose() * svd.U.Transpose());

            if (R.Determinant() < 0)
            {
                var VT_corrected = svd.VT.Clone();
                VT_corrected.SetRow(2, VT_corrected.Row(2) * -1f);
                R = (DenseMatrix)(VT_corrected.Transpose() * svd.U.Transpose());
            }

            var cSrcMat = DenseMatrix.OfColumnArrays(new[] { centroidSrc.X, centroidSrc.Y, centroidSrc.Z });
            var cDstMat = DenseMatrix.OfColumnArrays(new[] { centroidDst.X, centroidDst.Y, centroidDst.Z });
            var tMat = cDstMat - (R * cSrcMat);
            return (R, new Vector3(tMat[0, 0], tMat[1, 0], tMat[2, 0]));
        }

        private struct KdNodeStruct
        {
            public Vector3 Point;
            public int Left;
            public int Right;
        }

        private class KdTreeFlat
        {
            private readonly KdNodeStruct[] nodes;
            private int rootIndex = -1;

            public KdTreeFlat(List<Vector3> points)
            {
                var pts = points.ToArray();
                nodes = new KdNodeStruct[pts.Length];
                rootIndex = Build(pts, 0, pts.Length - 1, 0);
            }

            private int Build(Vector3[] points, int start, int end, int depth)
            {
                if (start > end) return -1;

                int axis = depth % 3;
                Array.Sort(points, start, end - start + 1, Comparer<Vector3>.Create((a, b) =>
                    axis == 0 ? a.X.CompareTo(b.X) : (axis == 1 ? a.Y.CompareTo(b.Y) : a.Z.CompareTo(b.Z))));

                int mid = start + (end - start) / 2;
                nodes[mid] = new KdNodeStruct
                {
                    Point = points[mid],
                    Left = Build(points, start, mid - 1, depth + 1),
                    Right = Build(points, mid + 1, end, depth + 1)
                };
                return mid;
            }

            public (Vector3 Point, float DistanceSq) FindNearest(Vector3 target)
            {
                if (rootIndex == -1) return (Vector3.Zero, float.MaxValue);
                int bestIndex = -1;
                float bestDistSq = float.MaxValue;
                Search(rootIndex, target, 0, ref bestIndex, ref bestDistSq);
                return (nodes[bestIndex].Point, bestDistSq);
            }

            private void Search(int nodeIndex, Vector3 target, int depth, ref int bestIndex, ref float bestDistSq)
            {
                if (nodeIndex == -1) return;

                ref var node = ref nodes[nodeIndex];
                float distSq = Vector3.DistanceSquared(node.Point, target);
                if (distSq < bestDistSq)
                {
                    bestDistSq = distSq;
                    bestIndex = nodeIndex;
                }

                int axis = depth % 3;
                float axisDist = axis == 0 ? target.X - node.Point.X : (axis == 1 ? target.Y - node.Point.Y : target.Z - node.Point.Z);
                int first = axisDist < 0 ? node.Left : node.Right;
                int second = axisDist < 0 ? node.Right : node.Left;

                Search(first, target, depth + 1, ref bestIndex, ref bestDistSq);
                if (axisDist * axisDist < bestDistSq)
                    Search(second, target, depth + 1, ref bestIndex, ref bestDistSq);
            }
        }
    }
}
